### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by AIyc-0101** [Zi-YuanYang/DC-SFL#1]
作者您好，我是初学者   处理不好您论文中的数据集，请问方便提供一下吗

**Comment by Zi-YuanYang** [comment]
很感谢对我们的工作感兴趣。但是很抱歉，我们用的是公开数据集，我们是不能够私自传播的。对于分割数据集可以几个病人在一个节点进行划分，对于重建数据集请使用[CTLib](https://github.com/xiawj-hub/CTLIB)进行仿真。

**Comment by AIyc-0101** [comment]
感谢您的回复

**Comment by AIyc-0101** [comment]
那可以发一下数据集文件结构吗    以确保我没有做错
