### ISSUE TITLE
数据集文件结构

### ISSUE THREAD

**Issue by AIyc-0101** [Zi-YuanYang/DC-SFL#2]
那可以发一下数据集文件结构吗    以确保我没有做错

_Originally posted by @AIyc-0101 in https://github.com/Zi-YuanYang/DC-SFL/issues/1#issuecomment-1857501677_

**Comment by Zi-YuanYang** [comment]
> ```
>           那可以发一下数据集文件结构吗    以确保我没有做错
> ```
> 
> _Originally posted by @AIyc-0101 in [#1 (comment)](https://github.com/Zi-YuanYang/DC-SFL/issues/1#issuecomment-1857501677)_

每个节点的数据集单独放一个文件夹即可
